name: Pseudo Marketplace Action
description: |
  N/A

  ## Usage

  ```yaml
    steps:
      - name: Pseudo Marketplace
        uses: tmknom/pseudo-marketplace-action@v0
  ```

runs:
  using: composite

  steps:
    - name: Run
      shell: bash
      run: |
        set -x
        echo "Write steps"
